flask-logging:
  build: ./flask-login-logging/
  command: python "echo login logggin"
  volumes:
    - .:/code
  ports:
    - "5000:5000"

flask-login-decorator:
  build: ./flask-login-decorator/
  command: python "echo flask login decorator"
  volumes:
    - .:/code
  ports:
    - "5001:5001"

flask-rest-sqlite:
  build: ./flask-rest-sqlite/
  command: python "echo flask rest sqlite"
  volumes:
    - .:/code
  ports:
    - "5002:5002"

flask-cache:
  build: ./flask-cache/
  command: python "echo flask celery"
  volumes:
    - .:/code
  ports:
    - "5002:5001"
