flask-logging:
  build: ./flask-login-logging/
  command: python "echo"
  volumes:
    - .:/code
  ports:
    - "5000:5000"

flask-login-decorator:
  build: ./flask-login-decorator/
  command: python "echo"
  volumes:
    - .:/code
  ports:
    - "5001:5001"

flask-rest-sqlite:
  build: ./flask-rest-sqlite/
  command: python "echo"
  volumes:
    - .:/code
  ports:
    - "5002:5002"
