flask-cache:
  build: ./flask-cache/
  command: python "echo flask cache"
  volumes:
    - .:/code
  ports:
    - "5001:5001"

flask-logging:
  build: ./flask-login-logging/
  command: python "echo flask logggin"
  volumes:
    - .:/code
  ports:
    - "5002:5000"

flask-login-decorator:
  build: ./flask-login-decorator/
  command: python "echo flask login decorator"
  volumes:
    - .:/code
  ports:
    - "5003:5000"

flask-redis:
  build: ./flask-redis/
  command: python "echo flask redis"
  volumes:
    - .:/code
  ports:
    - "5004:5000"

flask-rest-sqlite:
  build: ./flask-rest-sqlite/
  command: python "echo flask rest sqlite"
  volumes:
    - .:/code
  ports:
    - "5005:5000"

flask-sendmail:
  build: ./flask-sendmail/
  command: python "echo flask send mail"
  volumes:
    - .:/code
  ports:
    - "5006:5000"
