version: '3.8'
services:
  rabbit_service:
    build:
      context: ./ampq/db
      dockerfile: ./Dockerfile
    volumes:
      - .rabbit_data:/var/data/
    expose:
      - 5432
    hostname: "rabbit-service"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq-service"
    volumes:
      - ".rabbit_data:/var/data/"
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
