apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
    - name: liveness
    image: k8s.gcr.io/liveness
      args:
      - /readiness
      livenessProbe:
        httpGet:
          path: /liveness
          port: 5000
          httpHeaders:
          - name: Custom-Header
            value: Awesome
        failureThreshold: 30
        initialDelaySeconds: 3
        periodSeconds: 3
        timeoutSeconds: 5
      readinessProbe:
        httpGet:
          path: /readiness
          port: 5000
          httpHeaders:
          - name: Custom-Header
            value: Awesome
        failureThreshold: 30
        initialDelaySeconds: 3
        periodSeconds: 3
        timeoutSeconds: 5
