# Docker-compose for Graylog

version: '3'
services:
  api1:
    build: ./api1
    container_name: "app1"
    restart: always
    ports:
        - "5001:5001"
  api2:
    build: ./api2
    container_name: "app2"
    restart: always
    ports:
        - "5002:5002"
    depends_on:
      - api1

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    networks:
      - app-tier
  myapp:
    image: 'myapp:latest'
    networks:
      - app-tier

  rabbit1:
  # image: "rabbitmq:3-management"
  buil: ./Dockerfile
  hostname: "rabbit1"
  environment:
    RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
    RABBITMQ_DEFAULT_USER: "rabbitmq"
    RABBITMQ_DEFAULT_PASS: "rabbitmq"
    RABBITMQ_DEFAULT_VHOST: "/"
  ports:
    - "15672:15672"
    - "5672:5672"
  labels:
    NAME: "rabbitmq1"
  volumes:
    - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
    
  networks:
    app-tier:
      driver: bridge
